[default]
embedding_model = "bedrock"
embedding_dim = 1536
embedding_batch_size = 100
embedding_provider = "bedrock"
embedding_model_name = "amazon.titan-embed-text-v1"

[bedrock]
region_name = "us-east-1"
model_id = "anthropic.claude-3-sonnet-20240229-v1:0"
max_tokens = 4096
temperature = 0.0

[llm]
provider = "bedrock"
model = "anthropic.claude-3-sonnet-20240229-v1:0"

[database]
provider = "cloud"
user = "default"
password = "default"
host = "api.r2r.cloud"
port = "443"
dbname = "default"
