# Standardized type mappings per database dialect
TYPE_MAPS: dict[str, dict[str, str]] = {
    "sqlite": {
        "INTEGER": "numeric",
        "REAL": "numeric",
        "TEXT": "string",
        "BLOB": "string",
        "NUMERIC": "numeric",
        "DATE": "datetime",
        "DATETIME": "datetime",
        "BOOLEAN": "bool",
        "INT": "numeric",
        "TINYINT": "numeric",
        "SMALLINT": "numeric",
        "MEDIUMINT": "numeric",
        "BIGINT": "numeric",
        "UNSIGNED BIG INT": "numeric",
        "DOUBLE": "numeric",
        "DOUBLE PRECISION": "numeric",
        "FLOAT": "numeric",
        "CHARACTER": "string",
        "VARCHAR": "string",
        "VARYING CHARACTER": "string",
        "NCHAR": "string",
        "NATIVE CHARACTER": "string",
        "NVARCHAR": "string",
        "CLOB": "string"
    },
    "snowflake": {
        "NUMBER": "numeric",
        "FLOAT": "numeric",
        "FLOAT4": "numeric",
        "FLOAT8": "numeric",
        "DOUBLE": "numeric",
        "DOUBLE PRECISION": "numeric",
        "REAL": "numeric",
        "DECIMAL": "numeric",
        "NUMERIC": "numeric",
        "INT": "numeric",
        "INTEGER": "numeric",
        "BIGINT": "numeric",
        "SMALLINT": "numeric",
        "BYTEINT": "numeric",
        "VARCHAR": "string",
        "CHAR": "string",
        "CHARACTER": "string",
        "STRING": "string",
        "TEXT": "string",
        "BINARY": "string",
        "VARBINARY": "string",
        "BOOLEAN": "bool",
        "DATE": "datetime",
        "DATETIME": "datetime",
        "TIME": "datetime",
        "TIMESTAMP": "datetime",
        "TIMESTAMP_NTZ": "datetime",
        "TIMESTAMP_LTZ": "datetime",
        "TIMESTAMP_TZ": "datetime"
    },
    "postgresql": {
        "SMALLINT": "numeric",
        "INTEGER": "numeric",
        "INT": "numeric",
        "BIGINT": "numeric",
        "DECIMAL": "numeric",
        "NUMERIC": "numeric",
        "REAL": "numeric",
        "DOUBLE PRECISION": "numeric",
        "SERIAL": "numeric",
        "BIGSERIAL": "numeric",
        "VARCHAR": "string",
        "CHAR": "string",
        "CHARACTER": "string",
        "TEXT": "string",
        "BOOLEAN": "bool",
        "BOOL": "bool",
        "DATE": "datetime",
        "TIMESTAMP": "datetime",
        "TIMESTAMPTZ": "datetime",
        "TIME": "datetime",
        "TIMETZ": "datetime",
        "BYTEA": "string",
        "JSON": "string",
        "JSONB": "string",
        "UUID": "string",
        "INET": "string",
        "CIDR": "string",
        "MACADDR": "string",
        "XML": "string"
    },
    "mssql": {
        "BIT": "bool",
        "TINYINT": "numeric",
        "SMALLINT": "numeric",
        "INT": "numeric",
        "BIGINT": "numeric",
        "DECIMAL": "numeric",
        "NUMERIC": "numeric",
        "MONEY": "numeric",
        "SMALLMONEY": "numeric",
        "FLOAT": "numeric",
        "REAL": "numeric",
        "VARCHAR": "string",
        "NVARCHAR": "string",
        "CHAR": "string",
        "NCHAR": "string",
        "TEXT": "string",
        "NTEXT": "string",
        "DATE": "datetime",
        "DATETIME": "datetime",
        "DATETIME2": "datetime",
        "SMALLDATETIME": "datetime",
        "TIME": "datetime",
        "DATETIMEOFFSET": "datetime",
        "BINARY": "string",
        "VARBINARY": "string",
        "IMAGE": "string",
        "UNIQUEIDENTIFIER": "string",
        "XML": "string"
    },
}


RESERVED_KEYWORDS: dict[str, set] = {
    "sqlite": {
        "ABORT", "ACTION", "ALWAYS", "ANALYZE", "ATTACH", "AUTOINCREMENT", "BEGIN",
        "COMMIT", "CONFLICT", "DEFERRED", "DETACH", "ESCAPE", "EXCLUDE", "EXCLUSIVE",
        "EXPLAIN", "FAIL", "FILTER", "GLOB", "IGNORE", "IMMEDIATE", "INDEXED",
        "INSTEAD", "MATCH", "NO", "NOTHING", "NULLS", "OTHERS", "OVER", "PLAN",
        "PRAGMA", "PRECEDING", "QUERY", "RAISE", "RECURSIVE", "REINDEX", "SAVEPOINT",
        "TEMP", "TEMPORARY", "TIES", "TRANSACTION", "VACUUM", "WITHOUT"
    },
    "snowflake": {
        "ACCOUNT", "CONNECT", "CONNECTION", "CURRENT_USER", "FALSE", "GRANT",
        "ILIKE", "INCREMENT", "LOCK", "MINUS", "MODIFY", "ORGANIZATION", "RENAME",
        "SAMPLE", "SCHEMA", "SOME", "START", "TABLESAMPLE", "TRUE", "USER",
        "WHENEVER"
    },
    "postgresql": {
        "ANALYSE", "ANALYZE", "ARRAY", "ASYMMETRIC", "AUTHORIZATION", "BINARY",
        "BOTH", "COLLATION", "CONCURRENTLY", "CURRENT_CATALOG", "CURRENT_ROLE",
        "CURRENT_SCHEMA", "END", "EXCEPT", "FETCH", "FREEZE", "INITIALLY", "ISNULL",
        "LATERAL", "LEADING", "LOCALTIME", "LOCALTIMESTAMP", "ONLY", "OVERLAPS",
        "PLACING", "SESSION_USER", "SIMILAR", "SYMMETRIC", "TABLESAMPLE", "VARIADIC",
        "VERBOSE"
    },
    "mysql": {
        "ACCESSIBLE", "ASENSITIVE", "BIGINT", "BLOB", "CALL", "CHANGE", "CHAR",
        "CHARACTER", "CONDITION", "CONTINUE", "CONVERT", "CURSOR", "DATABASES",
        "DAY_HOUR", "DAY_MICROSECOND", "DAY_MINUTE", "DAY_SECOND", "DEC", "DECIMAL",
        "DECLARE", "DELAYED", "DESCRIBE", "DETERMINISTIC", "DISTINCTROW", "DIV",
        "DOUBLE", "DUAL", "ELSEIF", "ENCLOSED", "ESCAPED", "EXIT", "EXPLAIN", "FLOAT",
        "FLOAT4", "FLOAT8", "FORCE", "FULLTEXT", "GET", "HIGH_PRIORITY",
        "HOUR_MICROSECOND", "HOUR_MINUTE", "HOUR_SECOND", "INFILE", "INOUT",
        "INSENSITIVE", "INT", "INT1", "INT2", "INT3", "INT4", "INT8", "INTEGER",
        "INTERVAL", "IO_AFTER_GTIDS", "IO_BEFORE_GTIDS", "ITERATE", "KEYS", "KILL",
        "LEAVE", "LINEAR", "LINES", "LOAD", "LONG", "LONGBLOB", "LONGTEXT", "LOOP",
        "LOW_PRIORITY", "MASTER_BIND", "MASTER_SSL_VERIFY_SERVER_CERT", "MAXVALUE",
        "MEDIUMBLOB", "MEDIUMINT", "MEDIUMTEXT", "MIDDLEINT", "MINUTE_MICROSECOND",
        "MINUTE_SECOND", "MOD", "MODIFIES", "NO_WRITE_TO_BINLOG", "NUMERIC",
        "OPTIMIZE", "OPTIMIZER_COSTS", "OPTION", "OPTIONALLY", "OUT", "OUTFILE",
        "PARTITION", "PRECISION", "PROCEDURE", "PURGE", "RANGE", "READ", "READS",
        "READ_WRITE", "REAL", "REGEXP", "REPEAT", "RESIGNAL", "RETURN", "REVOKE",
        "RLIKE", "SCHEMAS", "SECOND_MICROSECOND", "SENSITIVE", "SEPARATOR", "SHOW",
        "SIGNAL", "SMALLINT", "SPATIAL", "SPECIFIC", "SQL", "SQLEXCEPTION",
        "SQLSTATE", "SQLWARNING", "SQL_BIG_RESULT", "SQL_CALC_FOUND_ROWS",
        "SQL_SMALL_RESULT", "SSL", "STARTING", "STORED", "STRAIGHT_JOIN", "TERMINATED",
        "TINYBLOB", "TINYINT", "TINYTEXT", "TRAILING", "UNDO", "UNLOCK", "UNSIGNED",
        "USAGE", "USE", "UTC_DATE", "UTC_TIME", "UTC_TIMESTAMP", "VARBINARY",
        "VARCHAR", "VARCHARACTER", "VARYING", "WHILE", "WRITE", "XOR", "YEAR_MONTH",
        "ZEROFILL"
    },
    "general": {
        "ADD", "ALL", "ALTER", "AND", "ANY", "AS", "ASC", "BEFORE", "BETWEEN",
        "BINARY", "BOTH", "BY", "CASCADE", "CASE", "CAST", "CHECK", "COLLATE",
        "COLUMN", "CONSTRAINT", "CREATE", "CROSS", "CURRENT", "CURRENT_DATE",
        "CURRENT_TIME", "CURRENT_TIMESTAMP", "DATABASE", "DEFAULT", "DEFERRABLE",
        "DELETE", "DESC", "DISTINCT", "DO", "DROP", "EACH", "ELSE", "EXISTS", "FALSE",
        "FETCH", "FOLLOWING", "FOR", "FOREIGN", "FROM", "FULL", "GENERATED", "GRANT",
        "GROUP", "HAVING", "IF", "IGNORE", "ILIKE", "IN", "INDEX", "INNER", "INSERT",
        "INTERSECT", "INTO", "IS", "JOIN", "KEY", "LEFT", "LIKE", "LIMIT", "LOCK",
        "MATCH", "NATURAL", "NOT", "NULL", "OF", "OFFSET", "ON", "OR", "ORDER",
        "OUTER", "PARTITION", "PRIMARY", "RANGE", "REFERENCES", "REGEXP", "RELEASE",
        "RENAME", "REPLACE", "RESTRICT", "RETURNING", "RIGHT", "ROLLBACK", "ROW",
        "ROWS", "SCHEMA", "SELECT", "SET", "SOME", "TABLE", "THEN", "TO", "TRIGGER",
        "TRUE", "UNION", "UNIQUE", "UPDATE", "USER", "USING", "VALUES", "VIEW",
        "VIRTUAL", "WHEN", "WHERE", "WINDOW", "WITH"
    },
}


CHAR_REPLACEMENTS: dict[str, str] = {
    '²': '2', '³': '3', '¹': '1', '°': 'deg', 'µ': 'u',
    '©': 'copyright', '®': 'registered', '™': 'tm',
    '€': 'eur', '£': 'gbp', '¥': 'jpy', '¢': 'cent',
    '¼': '1_4', '½': '1_2', '¾': '3_4',
    '+': '_plus_', '<': 'lt', '>': 'gt', '|': '_',
}
